name: flutter_plcweb
description: AFT-PLC-WEB - Sistema de monitoramento de equipamentos industriais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  
  # Functional Programming - IMPORTANTE!
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Utilities
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Navigation
  go_router: ^15.1.3
  
  # Forms & Validation
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  
  # Connectivity
  connectivity_plus: ^6.1.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date & Time
  intl: ^0.20.2
  
  # Device Info
  device_info_plus: ^11.4.0
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Location
  geolocator: ^14.0.1
  
  # Bluetooth
  flutter_blue_plus: ^1.31.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8