name: flutter_plcweb
description: AFT-PLC-WEB - Sistema de monitoramento de equipamentos industriais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  
  # UI e Utilidades
  flutter_blue_plus: ^1.31.0  # Bluetooth
  geolocator: ^10.1.0         # GPS
  excel: ^3.0.0               # Exportar Excel
  csv: ^5.1.1                 # Exportar CSV
  image_picker: ^1.0.5        # Fotos
  
  # Gerenciamento de Estado
  provider: ^6.1.1            # Mais simples
  
  # Notificações
  flutter_local_notifications: ^16.2.0
  
  # UI Components
  flutter_spinkit: ^5.2.0     # Loading animations
  fluttertoast: ^8.2.4        # Toast messages
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8