name: flutter_plcweb
description: AFT-PLC-WEB - Sistema de monitoramento de equipamentos industriais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Utilidades
  flutter_blue_plus: ^1.31.0  # Bluetooth
  geolocator: ^14.0.2         # GPS
  excel: ^4.0.6               # Exportar Excel
  csv: ^6.0.0                 # Exportar CSV
  image_picker: ^1.0.5        # Fotos
  
  # Gerenciamento de Estado
  provider: ^6.1.1            # Mais simples
  
  # Notificações
  flutter_local_notifications: ^19.3.0
  
  # UI Components
  flutter_spinkit: ^5.2.0     # Loading animations
  fluttertoast: ^8.2.4        # Toast messages

  js: ^0.7.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  assets:
    - assets/images/logo.png